version: "3"
services:
  coap-calculator-simple:
    labels:
      - traefik.udp.routers.coap-calculator-simple.entrypoints=coap-calculator-simple
    build:
      context: ./things/calculator/
      dockerfile: ./coap/js/Dockerfile-simple
  coap-calculator-content-negotiation:
    labels:
      - traefik.udp.routers.coap-calculator-content-negotiation.entrypoints=coap-calculator-content-negotiation
    build:
      context: ./things/calculator/
      dockerfile: ./coap/js/Dockerfile-contentneg
  http-express-calculator-simple:
    labels:
      - traefik.http.routers.http-express-calculator-simple.rule=PathPrefix(`/http-express-calculator-simple`)
    build:
      context: ./things/calculator/
      dockerfile: ./http/express/Dockerfile-simple
  http-express-calculator-content-negotiation:
    labels:
      - traefik.http.routers.http-express-calculator-content-negotiation.rule=PathPrefix(`/http-express-calculator-content-negotiation`)
    build:
      context: ./things/calculator/
      dockerfile: ./http/express/Dockerfile-contentneg
  http-flask-calculator:
    labels:
      - traefik.http.routers.http-flask-calculator.rule=PathPrefix(`/http-flask-calculator`)
    build:
      context: ./things/calculator/
      dockerfile: ./http/flask/Dockerfile
  mqtt-calculator:
    build:
      context: ./things/calculator/
      dockerfile: ./mqtt/js/Dockerfile
  modbus-elevator:
    labels:
      - traefik.tcp.routers.modbus-elevator.entrypoints=modbus-elevator
      - traefik.tcp.routers.modbus-elevator.rule=HostSNI(`*`)
    build:
      context: ./things/elevator/
      dockerfile: ./modbus/js/Dockerfile
  reverse-proxy:
    image: traefik:v3.0
    command: 
      - "--log.level=DEBUG"
      - "--api.insecure=true" 
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.modbus-elevator.address=:3179"
      - "--entrypoints.coap-calculator-simple.address=:5683/udp"
      - "--entrypoints.coap-calculator-content-negotiation.address=:5684/udp"
    ports:
      - "80:80"
      - "3179:3179"
      - "5683:5683/udp"
      - "5684:5684/udp"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
